backend:
  name: git-gateway
  branch: master
media_folder: "public/img"
public_folder: "/img"
collections:
  - name: "link"
    label: "Link Page"
    folder: "links"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Theme Color"
        name: themeColor
        widget: "string"
        hint: "Theme color that will be applied to button and active pagination, defaults to light blue"
        pattern:
          [
            "^#[0-9|A-F|a-f]{6}$",
            "Should fill with valid color hex (# followed by 6 character)",
          ]
        default: "#63B3ED"
        required: false
      - label: "Theme Text Color"
        name: themeTextColor
        widget: "string"
        hint: "Text color in the button. Sometimes you need it dark or light. If not specified will be automatically determined"
        pattern:
          [
            "^#[0-9|A-F|a-f]{6}$",
            "Should fill with valid color hex (# followed by 6 character)",
          ]
        default: "#ffffff"
        required: false
      - label: "Slide Show"
        name: "gallery"
        description: Link is a single page containing a product which have a gallery and CTA buttons
        widget: "list"
        fields:
          - { label: Image, name: image, widget: image }
          - { label: "Image Title", name: title, widget: string }
          - { label: "Image Description", name: content, widget: text }
      - label: "Button List"
        name: "buttons"
        widget: list
        fields:
          - { label: "Button Text", name: text, widget: string }
          - { label: "Button URL", name: link, widget: string }
