backend:
  name: git-gateway
  branch: master
  media_folder: "public/img"
  collections:
    - name: "link"
      label: "Link Page"
      folder: "links"
      create: true
      slug: { { slug } }
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - label: "Slide Show"
          name: "slideshow"
          widget: "list"
          fields:
            - { label: Image, name: slideshowImage, widget: image }
            - { label: "Image Title", name: slideshowTitle, widget: string }
            - { label: "Image Description", name: slideshowDesc, widget: text }
        - label: "Button List"
          name: "buttonlist"
          widget: list
          fields:
            - { label: "Button Text", name: buttonText, widget: string }
            - { label: "Button URL", name: buttonURL, widget: string }
