backend:
  name: git-gateway
  branch: master
media_folder: "public/img"
public_folder: "/img"
collections:
  - name: "link"
    label: "Link Page"
    folder: "links"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }

      - label: "Logo"
        name: logo
        widget: "image"
        hint: "Best using square logo"

      - label: "Background Color"
        name: backgroundColor
        widget: "string"
        hint: "Background color for the page"
        pattern:
          [
            "^#[0-9|A-F|a-f]{6}$",
            "Should fill with valid color hex (# followed by 6 character)",
          ]
        default: "#ffffff"

      - label: "Text Color"
        name: textColor
        widget: "string"
        hint: "Text color for most of the text within the page"
        pattern:
          [
            "^#[0-9|A-F|a-f]{6}$",
            "Should fill with valid color hex (# followed by 6 character)",
          ]
        default: "#2f2f2f"

      - label: "Accent Color"
        name: accentColor
        widget: "string"
        hint: "Secondary color for accent. Will be used on button"
        pattern:
          [
            "^#[0-9|A-F|a-f]{6}$",
            "Should fill with valid color hex (# followed by 6 character)",
          ]
        default: "#035aa6"

      - label: "Button Text Color"
        name: buttonTextColor
        widget: "string"
        hint: "Text color in the button. Different from text color because it will be displayed over accent color"
        pattern:
          [
            "^#[0-9|A-F|a-f]{6}$",
            "Should fill with valid color hex (# followed by 6 character)",
          ]
        default: "#ffffff"

      - label: "Slide Show"
        name: "gallery"
        description: Link is a single page containing a product which have a gallery and CTA buttons
        widget: "list"
        fields:
          - { label: Image, name: image, widget: image }
          - { label: "Image Title", name: title, widget: string }
          - { label: "Image Description", name: content, widget: text }

      - label: "Button With Tray List"
        name: "trayButtons"
        description: Button that will open a tray that contains more link
        widget: list
        fields:
          - label: Button Text
            name: trayTriggerText
            widget: string
          - label: Tray Title
            name: trayTitle
            widget: string
          - label: Tray Subtitle
            name: traySubtitle
            widget: string
          - label: Tray Buttons
            name: buttons
            widget: "list"
            fields:
              - {
                  label: "Button Icon",
                  name: icon,
                  widget: image,
                  hint: Please use existing image if there's any (e.g.),
                }
              - { label: "Button Text", name: text, widget: string }
              - { label: "Button URL", name: link, widget: string }

      - label: "Button List"
        name: "buttons"
        description: Button that contains url and clickable to external link
        widget: list
        fields:
          - { label: "Button Text", name: text, widget: string }
          - { label: "Button URL", name: link, widget: string }
