backend:
  name: git-gateway
  branch: master
media_folder: "public/img"
public_folder: "/img"
collections:
  - name: "link"
    label: "Link Page"
    folder: "links"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Slide Show"
        name: "gallery"
        widget: "list"
        fields:
          - { label: Image, name: image, widget: image }
          - { label: "Image Title", name: title, widget: string }
          - { label: "Image Description", name: content, widget: text }
      - label: "Button List"
        name: "buttons"
        widget: list
        fields:
          - { label: "Button Text", name: text, widget: string }
          - { label: "Button URL", name: link, widget: string }
